In [1]:
import csv
import math
import random
import numpy as np 
import pandas as pd 
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score,roc_auc_score, roc_curve
from sklearn.metrics import plot_confusion_matrix, classification_report
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
from sklearn import neighbors

df_train = pd.read_csv('../data_preprocess_v2/train_df_day_5_1.csv')
df_test = pd.read_csv('../data_preprocess_v2/test_df_day_5_1.csv')

In [2]:
X_train = df_train[df_train.columns[0:10]]
y_train = df_train['Close (t)']
X_test = df_test[df_test.columns[0:10]]
y_test = df_test['Close (t)']

In [3]:
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [34]:
knn = neighbors.KNeighborsRegressor(n_neighbors = 3, metric='euclidean')
knn_model = knn.fit(X_train, y_train)

In [35]:
y_pred = knn.predict(X_test)

In [36]:
y_pred

array([0.9892    , 1.24036667, 1.1017    , ..., 2.2278    , 2.1381    ,
       2.22093333])

In [37]:
mvt_pred = np.where(y_pred > df_test['Close (t-1)'], 1, 0)

In [38]:
mvt_pred

array([0, 1, 0, ..., 0, 0, 0])

In [39]:
mvt_test = df_test['movement']
#mvt_test = mvt_test.to_numpy()

In [40]:
mvt_test

0       0
1       1
2       1
3       0
4       1
       ..
1531    0
1532    1
1533    1
1534    1
1535    0
Name: movement, Length: 1536, dtype: int64

In [41]:
def evaluate_model(model, predicted, label_test):

    print("accuracy:", str(accuracy_score(label_test, predicted)))
    
    print("precision:", str(precision_score(label_test, predicted, average='weighted')))

    print("recall:", str(recall_score(label_test, predicted, average='weighted')))
   
    print("f1", str(f1_score(label_test, predicted, average='weighted')))
    
    print("metrics.roc_auc_score", str(roc_auc_score(label_test, predicted, average='weighted')))

    plot_confusion_matrix(model, predicted, label_test,
                      display_labels=list(set(label_test)),
                      cmap=plt.cm.Blues)
    
    classification = classification_report(label_test, predicted)
    print(classification)

In [42]:
evaluate_model(knn_model, mvt_pred, mvt_test)

accuracy: 0.5065104166666666
precision: 0.5056037337399647
recall: 0.5065104166666666
f1 0.4821317194560522
metrics.roc_auc_score 0.5045347802127931


ValueError: plot_confusion_matrix only supports classifiers

In [43]:
print(confusion_matrix(mvt_test, mvt_pred))
print(classification_report(mvt_test, mvt_pred))

[[559 216]
 [542 219]]
              precision    recall  f1-score   support

           0       0.51      0.72      0.60       775
           1       0.50      0.29      0.37       761

    accuracy                           0.51      1536
   macro avg       0.51      0.50      0.48      1536
weighted avg       0.51      0.51      0.48      1536

